language: ruby
rvm:
  - 2.0.0
  - 1.9.3
  - jruby
  - rbx-19mode
gemfile:
  - test/gemfiles/sass_3_2.gemfile
  - test/gemfiles/sass_head.gemfile
matrix:
  allow_failures:
    - gemfile: test/gemfiles/sass_head.gemfile
