language: ruby
rvm:
  - 2.0.0
  - 1.9.3
  - jruby
  - rbx-2.2.4
gemfile:
  - test/gemfiles/sass_3_2.gemfile
  - test/gemfiles/sass_head.gemfile
before_install:
  - "npm install node-sass"
matrix:
  allow_failures:
    - gemfile: test/gemfiles/sass_head.gemfile
