language: ruby
sudo: false
rvm:
  - 2.2.3
gemfile:
  - test/gemfiles/rails_4_2.gemfile
  - test/gemfiles/rails_head.gemfile
cache: bundler
bundler_args: --path ../../vendor/bundle --without debug
notifications:
  slack: heybb:3n88HHilXn76ji9vV4gL819Y
env:
  global:
  - VERBOSE=1
script:
  bundle exec rake
